import axios from 'axios';

export async function generatePatchFromPrompt(prompt: string) {
  const apiKey = process.env.LLM_API_KEY;
  if (!apiKey) {
    return generateMockPatch(prompt);
  }
  try {
    const system = 'You are a helpful code assistant. Respond with valid JSON only with keys: title, pr_body, files where files is an array of {path, content}.';
    const resp = await axios.post('https://api.openai.com/v1/chat/completions', {
      model: process.env.LLM_MODEL || 'gpt-4o-mini',
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: prompt }
      ],
      temperature: 0.2,
      max_tokens: 1500
    }, {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      }
    });
    const text = resp.data?.choices?.[0]?.message?.content || resp.data?.choices?.[0]?.text || '';
    try {
      return JSON.parse(text);
    } catch (err) {
      const m = text.match(/\{[\s\S]*\}/m);
      if (m) return JSON.parse(m[0]);
      return { title: `Suggestion for: ${prompt.substring(0, 60)}`, pr_body: 'Automated suggestion', files: [{ path: `.github/agent-suggestions/suggestion-${Date.now()}.md`, content: text }] };
    }
  } catch (err) {
    console.error('LLM call failed, falling back to mock', err);
    return generateMockPatch(prompt);
  }
}

export async function generateMockPatch(prompt: string) {
  return {
    title: `Agent suggestion: ${prompt.substring(0, 60)}`,
    pr_body: `Automated suggestion generated by agent for: ${prompt}`,
    files: [
      {
        path: `.github/agent-suggestions/suggestion-${Date.now()}.md`,
        content: `Suggested changes for: ${prompt}\n\n(this is a mock suggestion)\n`
      }
    ]
  };
}

export default { generatePatchFromPrompt, generateMockPatch };
